models/Blog.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "{{%blog}}".
 *
 * @property integer $id
 * @property string $name
 * @property string $text
 * @property integer $category_id
 * @property integer $user_id
 * @property integer $create_time
 * @property integer $update_time
 * @property integer $type
 * @property string $keywords
 * @property string $description
 * @property string $image
 * @property string $alias
 * @property integer $views
 */
class Blog extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%blog}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['text', 'keywords', 'description'], 'required'],
            [['text', 'keywords', 'description'], 'string'],
            [['category_id', 'user_id', 'create_time', 'update_time', 'type', 'views'], 'integer'],
            [['name', 'image', 'alias'], 'string', 'max' => 256],

            [['category_id', 'user_id', 'create_time', 'update_time', 'type', 'views'], 'default', 'value' => 0],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'text' => 'Text',
            'category_id' => 'Category ID',
            'user_id' => 'User ID',
            'create_time' => 'Create Time',
            'update_time' => 'Update Time',
            'type' => 'Type',
            'keywords' => 'Keywords',
            'description' => 'Description',
            'image' => 'Image',
            'alias' => 'Alias',
            'views' => 'Views',
        ];
    }

    public function beforeSave($insert)
    {
        if ($this->isNewRecord) {
            $this->create_time = time();
        } else {
            $this->update_time = time();
        }
        $this->user_id = Yii::$app->user->id;
        return parent::beforeSave($insert);
    }

    public function getCategory()
    {
        return $this->hasOne(BlogCategory::className(), ['id' => 'category_id']);
    }

    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }

    public function getComments()
    {
        return $this->hasMany(Comments::className(), ['blog_id' => 'id']);
    }
}

models/Organizer.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "{{%organizer}}".
 *
 * @property integer $id
 * @property string $name
 * @property string $full_name 
 * @property string $contact_person
 * @property string $address
 * @property string $inn
 * @property string $kpp 
 * @property string $ogrn 
 * @property string $okpo 
 * @property string $okpf 
 * @property string $email
 * @property string $phone
 * @property string $fedresurs_link
 *
 * @property Lot[] $lots
 */
class Organizer extends \yii\db\ActiveRecord
{
    public static function tableName()
    {
        return '{{%organizer}}';
    }

    public function rules()
    {
        return [
            [['region_id', 'inn', 'kpp', 'ogrn', 'okpo', 'type'], 'integer'],
            [['short_name', 'full_name', 'contact_person', 'address', 'email', 'fedresurs_link'], 'string', 'max' => 512],
            [['okpf', 'phone'], 'string', 'max' => 128],
        ];
    }

    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'short_name' => 'Наименомание',
            'full_name' => 'Полное наименомание',
            'contact_person' => 'Контактное лицо',
            'region_id' => 'Регион',
            'address' => 'Адрес',
            'inn' => 'ИНН',
            'kpp' => 'КПП',
            'ogrn' => 'ОГРН',
            'okpo' => 'ОКПО',
            'okpf' => 'ОКПФ',
            'email' => 'Email',
            'phone' => 'Телефон',
            'type' => 'Тип (ИП/ООО)',
            'fedresurs_link' => 'Федресурс',
        ];
    }

    public function getLots()
    {
        return $this->hasMany(Lot::className(), ['organizer_id' => 'id']);
    }
    public function getRegion()
    {
        return $this->hasOne(Region::className(), ['id' => 'region_id']);
    }
}

controllers/OrganizersController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Organizer;
use app\models\OrganizerSearch;
use app\models\Lot;

use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

class OrganizersController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['create', 'update', 'delete'],
                'rules' => [
                    // разрешаем модераторам и выше
                    [
                        'allow' => true,
                        'roles' => ['moder'],
                    ],
                ],
            ],  
        ];
    }

    public function actionIndex()
    {
        $searchModel = new OrganizerSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('index', [
            'searchModel' => $searchModel, 
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionView($id)
    {
        return $this->render(\app\models\User::isClient() ? 'view' : 'view-guest', [
            'model' => $this->findModel($id),
            'lots' => Lot::find()
                ->where(['organizer_id' => $id])
                ->limit(10)
                ->orderBy(['id' => SORT_DESC])
                ->all(),
        ]);
    }

    public function actionCreate()
    {
        $model = new Organizer();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    protected function findModel($id)
    {
        if (($model = Organizer::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/organizers/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

?>

<div class="organizer-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'short_name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'contact_person')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'address')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'inn')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'phone')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'fedresurs_link')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/organizers/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

?>

<div class="organizer-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'short_name') ?>

    <?= $form->field($model, 'contact_person') ?>

    <?= $form->field($model, 'address') ?>

    <?= $form->field($model, 'inn') ?>

    <?php // echo $form->field($model, 'email') ?>

    <?php // echo $form->field($model, 'phone') ?>

    <?php // echo $form->field($model, 'fedresurs_link') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/organizers/create.php
<?php

use yii\helpers\Html;

$this->title = 'Create Organizer';
$this->params['breadcrumbs'][] = ['label' => 'Organizers', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="organizer-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/organizers/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;

$this->title = Yii::$app->params['meta']['title']['organizers'];
$this->registerMetaTag(['name' => 'description', 'content' => Yii::$app->params['meta']['desc']['organizers']]);

$this->params['breadcrumbs'][] = Yii::$app->params['meta']['h1']['organizers'];
?>
<div class="organizer-index">

<h1><?= Html::encode(Yii::$app->params['meta']['h1']['organizers']) ?></h1>
<?php // echo $this->render('_search', ['model' => $searchModel]); ?>
<div class="row">
    <div class="col-lg-12">
        <?php if (\app\models\User::isClient() ): ?>
                
        <div class="panel panel-default">
            <div class="panel-body">
            <?php Pjax::begin(); ?>    <?= GridView::widget([
                    'dataProvider' => $dataProvider,
                    'filterModel' => $searchModel,
                    'columns' => [
                        ['class' => 'yii\grid\SerialColumn'],
                        'short_name',
                        'inn',
                        'address',
                        'phone',
                        // 'email:email',
                        // 'fedresurs_link',

                        [
                            'class' => 'yii\grid\ActionColumn',
                            'template' => '{view}',
                        ],
                    ],
                ]); ?>
            <?php Pjax::end(); ?>
            </div>
        </div>
        
        <?php else: ?>
            <?php echo $this->render('/site/noaccess'); ?>
        <?php endif ?>
        
    </div>
</div>



</div>

views/organizers/update.php
<?php

use yii\helpers\Html;

$this->title = 'Update Organizer: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Organizers', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="organizer-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/organizers/view-guest.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\helpers\Url;
use yii\helpers\StringHelper;

$this->title = $model->short_name;
$this->params['breadcrumbs'][] = ['label' => 'Организаторы торгов', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="organizer-view">

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-body">
                <h1 class="custom-header"><?= Html::encode($this->title) ?></h1>
                
                <table class="table table-striped table-bordered">
                    <colgroup> <col class="col-lg-3"> <col class="col-lg-9"> </colgroup>
                    <tbody>
                        <tr>
                            <th>Полное наименование</th>
                            <td><?=$model->full_name?> </td>
                        </tr>
                        <tr>
                            <th>Регион</th>
                            <td>▒▒▒▒▒▒▒▒ </td>
                        </tr>
                        <tr>
                            <th>Адрес</th>
                            <td>▒▒▒▒▒▒▒▒ </td>
                        </tr>
                        <tr>
                            <th>Телефон</th>
                            <td>▒▒▒▒▒▒▒▒  </td>
                        </tr>
                        <tr>
                            <th>Email</th>
                            <td>▒▒▒▒▒▒▒▒ </td>
                        </tr>
                        <tr>
                            <th>ИНН</th>
                            <td>▒▒▒▒▒▒▒▒ </td>
                        </tr>
                        <tr>
                            <th>ОГРН</th>
                            <td>▒▒▒▒▒▒▒▒ </td>
                        </tr>
                        <tr>
                            <th>Ссылка на федресурс</th>
                            <td><i class="fa fa-external-link"></i> ▒▒▒▒▒▒▒▒</td>
                        </tr>
                    </tbody>
                </table>


            </div>
        </div>
    </div>
</div>



<div class="row">
    <div class="col-lg-12">

        <div class="panel panel-default">
            <div class="panel-heading custom-panel-heading">Последние торги</div>
            <div class="panel-body lots-list-panel">
                <p><?php echo $this->render('/site/noaccess'); ?></p>
            </div>
        </div>

    </div>
</div>







</div>

views/organizers/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\helpers\Url;
use yii\helpers\StringHelper;

$this->title = $model->short_name;
$this->params['breadcrumbs'][] = ['label' => 'Организаторы торгов', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="organizer-view">

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-body">
                <h1 class="custom-header"><?= Html::encode($this->title) ?></h1>
                
                <table class="table table-striped table-bordered">
                    <colgroup> <col class="col-lg-3"> <col class="col-lg-9"> </colgroup>
                    <tbody>
                        <tr>
                            <th>Полное наименование</th>
                            <td><?=$model->full_name?> </td>
                        </tr>
                        <tr>
                            <th>Регион</th>
                            <td><?=$model->region->name?> </td>
                        </tr>
                        <tr>
                            <th>Адрес</th>
                            <td><?=$model->address?> </td>
                        </tr>
                        <tr>
                            <th>Телефон</th>
                            <td><?=$model->phone ? $model->phone : 'Неизвестно'?> </td>
                        </tr>
                        <tr>
                            <th>Email</th>
                            <td><?=$model->email ? $model->email : 'Неизвестно'?> </td>
                        </tr>
                        <tr>
                            <th>ИНН</th>
                            <td><?=$model->inn?> </td>
                        </tr>
                        <tr>
                            <th>ОГРН</th>
                            <td><?=$model->ogrn ? $model->ogrn : 'Неизвестно'?> </td>
                        </tr>
                        <tr>
                            <th>Ссылка на федресурс</th>
                            <td><i class="fa fa-external-link"></i> <a class="table-link" href="<?=$model->fedresurs_link?>"><?=$model->short_name?></a></td>
                        </tr>
                    </tbody>
                </table>


            </div>
        </div>
    </div>
</div>


<div class="row">
    <div class="col-lg-12">
         <?php if ($lots): ?>
        <div class="panel panel-default">
            <div class="panel-heading custom-panel-heading">Последние торги</div>
            <div class="panel-body lots-list-panel">
           
            <?php foreach ($lots as $model): ?>

                <div class="row lot-item">
                    <div class="col-lg-5">
                        <div class="lot-item-name">
                            <a data-pjax="0" class="table-link" href="<?= Url::to(['trade/view', 'id' => $model->id]); ?>">
                                Торги № <?= $model->id?> 
                            </a>
                        </div>
                        <p>
                            <span class="label label-primary">
                            <?php if ($model->type_id == 1): ?>
                                <i class="fa fa-arrow-down" style="color: orange;"></i> 
                            <?php else: ?>
                                <i class="fa fa-arrow-up" style="color: lime;"></i> 
                            <?php endif ?>
                                
                                <?= number_format($model->now_price, 2, ',', ' ')?> руб.
                            </span>
                        </p>
                        <p><?= StringHelper::truncate($model->description, 470, '...')?></p>
                    </div>
                    <div class="col-lg-3">
                        <p class="text-center pagado">Категория: <?= $model->category->name?></p>
                        <p class="text-center pagado">Регион: <?= $model->region->name?></p>
                        <p class="text-center pagado">Площадка: <?= $model->platform->name?></p>
                    </div>
                    <div class="col-lg-2">
                        <p class="text-center">
                            <?= Yii::$app->formatter->asDatetime($model->start_time, "php: d.m.y ") ?>
                            -
                            <?= Yii::$app->formatter->asDatetime($model->end_time, "php: d.m.y ") ?>
                        </p>
                        <p class="text-center pagado"><?= $model->status->name?></p>
                    </div>
                    <!-- <div class="col-lg-1"></div> -->
                    <div class="col-lg-2">
                    
                        <?php if (!Yii::$app->user->isGuest): ?>
                            <div class="text-center bs-component">
                                <?php if ($model->lotFavorite): ?>
                                    <button onclick="addFavorite(this)" data-id="<?= $model->id?>" type="button" class="add-favorite btn btn-xs btn-default" data-toggle="tooltip" data-placement="top" title="" data-original-title="Избранное">
                                        <i class="fa fa-minus"></i>
                                    </button>
                                <?php else: ?>
                                    <button onclick="addFavorite(this)" data-id="<?= $model->id?>" type="button" class="add-favorite btn btn-xs btn-success" data-toggle="tooltip" data-placement="top" title="" data-original-title="Избранное">
                                        <i class="fa fa-plus"></i>
                                    </button>
                                <?php endif ?>

                                <?php if ($model->lotMonitor): ?>
                                    <button onclick="addMonitor(this)" data-id="<?= $model->id?>" type="button" class="add-monitor btn btn-xs btn-default" data-toggle="tooltip" data-placement="top" title="" data-original-title="Следить">
                                        <i class="fa fa-search-minus"></i>
                                    </button>
                                <?php else: ?>
                                    <button onclick="addMonitor(this)" data-id="<?= $model->id?>" type="button" class="add-monitor btn btn-xs btn-warning" data-toggle="tooltip" data-placement="top" title="" data-original-title="Следить">
                                        <i class="fa fa-search-plus"></i>
                                    </button>
                                <?php endif ?>

                                <button onclick="addTrash(this)" data-id="<?= $model->id?>" type="button" class="add-trash btn btn-xs btn-danger" data-toggle="tooltip" data-placement="top" title="" data-original-title="Мусор">
                                    <i class="fa fa-trash"></i>
                                </button>
                            </div>
                        <?php endif ?>
                           

                    </div>
                </div>


                <?php endforeach ?>

            </div>
            <?php endif ?>


        </div>

    </div>
</div>








</div>