controllers/TradeController.php
<?php

namespace app\controllers;

use Yii;
use app\models\User;
use app\models\Lot;
use app\models\LotSearch;
use app\models\LotInterval;

use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

use app\components\CustomPagination;

class TradeController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['create', 'update', 'delete'],
                'rules' => [
                    // разрешаем модераторам и выше
                    [
                        'allow' => true,
                        'roles' => ['moder'],
                    ],
                ],
            ],        
        ];
    }

    // список лотов с фильтром
    public function actionIndex()
    {
        $searchModel = new LotSearch();
        $query = $searchModel->search(Yii::$app->request->post());

        $countQuery = clone $query;
        $pages = new CustomPagination(['totalCount' => $countQuery->count(), 'pageSize' => 10]);
        $pages->pageSizeParam = false;
        $lots = $query->offset($pages->offset)
            ->limit($pages->limit)
            ->all();


        // $lots = $query->all();
        return $this->render('index', [
            'searchModel' => $searchModel,
            'lots' => $lots,
            'pages' => $pages,
            'total' => $countQuery->count(),
        ]);

    }

    // просмотр отдельного лота
    public function actionView($id)
    {
        $lot = $this->findModelForView($id);

        $intervals = LotInterval::find()
            ->select(['start_time', 'price'])
            ->where(['lot_id' => $id])
            ->orderBy('start_time')
            ->asArray()
            ->all();
        $intervals = LotInterval::convert($intervals, $lot->now_price);


        return $this->render( User::isClient() ? 'view' : 'view-guest', 
        [
            'model' => $lot,
            'intervals' => $intervals,
        ]);
    }

    // добавить лот в избранное
    public function actionFavorite()
    {
        $id = Yii::$app->request->post('id');
        $this->findModel($id)->addFavorite();
        return $id;
    }

    // добавить лот в мусор
    public function actionTrash()
    {
        $id = Yii::$app->request->post('id');
        $this->findModel($id)->addTrash();
        return $id;
    }

    // следить за лотом
    public function actionMonitor()
    {
        $id = Yii::$app->request->post('id');
        $this->findModel($id)->addMonitor();
    }

    // создать новый лот
    public function actionCreate()
    {
        $model = new Lot();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    // редактировать лот
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save(false)) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    // удалить лот
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    // создать шаблон поиска
    public function actionCreateTemplate()
    {
        if (Yii::$app->request->isAjax) {
            if (User::isClient()) {
                $temp = new \app\models\LotTemplate;

                $name = Yii::$app->request->post('name');
                $temp->name = $name ? $name : 'Новый шаблон';
                $temp->user_id = Yii::$app->user->id;
                $temp->save(false);
            }
        }
        return $this->redirect(['index']);
    }

    // редактировать шаблон поиска
    public function actionEditTemplate()
    {
        if (Yii::$app->request->isAjax) {
            if (User::isClient()) {
                $temp = \app\models\LotTemplate::find()
                    ->where(['user_id' => Yii::$app->user->id, 'status' => 1])
                    ->one();

                $name = Yii::$app->request->post('name');
                $temp->name = $name ? $name : 'Новый шаблон';
                $temp->save(false);
            }
        }
        return $this->redirect(['index']);
    }

    // удалить шаблон поиска
    public function actionDeleteTemplate()
    {
        if (Yii::$app->request->isAjax) {
            if (User::isClient()) {
                $query = \app\models\LotTemplate::find()
                    ->where(['user_id' => Yii::$app->user->id]);

                // если у пользователя больше 1 шаблона
                if ($query->count() > 1) {
                    // удаляем активный
                    $temp = \app\models\LotTemplate::find()
                        ->where(['user_id' => Yii::$app->user->id, 'status' => 1])
                        ->one();
                    $temp->delete();

                    // делаем активным другой шаблон
                    $totemp = \app\models\LotTemplate::find()
                        ->where(['user_id' => Yii::$app->user->id])->one();
                    $totemp->status = 1;
                    $totemp->save(false);
                } 
            }
        }
        return $this->redirect(['index']);
    }

    // экспорт в excel
    public function actionExport()
    {
        if (!Yii::$app->user->isGuest) {

            $searchModel = new LotSearch();
            $lots = $searchModel->searchForExport()
                ->limit(100)
                ->all();

            $file = \moonland\phpexcel\Excel::widget([
                'models' => $lots,
                'mode' => 'export',
                'columns' => [
                    'id',
                    'name',
                    'description',
                    'region.name',
                    'type.name',
                    'status.name',
                    'category.name',
                    'platform.name',
                    'start_price',
                    'now_price',
                    'deposit_price',
                    'auct_step',
                    'market_price',
                    'publish_time:date',
                    'start_time:date',
                    'end_time:date',
                    'auction_time:date',
                    'result_time:date',
                    'debtor.name',
                    'organizer.name',
                    'link',
                    'fedresurs_link',
                ], 
            ]);
        }
        return $this->redirect(['index']);
    }

    // поиск лота по id
    protected function findModel($id)
    {
        if (($model = Lot::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    protected function findModelForView($id)
    {
        $model = Lot::find()
            ->from('{{%lot}} l')
            ->andWhere(['l.id' => $id]);

        if (!Yii::$app->user->isGuest) {
            $model->joinWith('lotFavorite fav',  true, 'LEFT JOIN')
                ->joinWith('lotTrash tr',  true, 'LEFT JOIN')
                ->joinWith('lotMonitor mon',  true, 'LEFT JOIN');
        }

        $model = $model->one();

        if ($model !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

}

views/trade/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

?>

<div class="lot-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'description')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'address')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'region_id')->textInput() ?>

    <?= $form->field($model, 'type_id')->textInput() ?>

    <?= $form->field($model, 'status_id')->textInput() ?>

    <?= $form->field($model, 'category_id')->textInput() ?>

    <?= $form->field($model, 'platform_id')->textInput() ?>

    <?= $form->field($model, 'start_price')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'now_price')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'market_price')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'deposit_price')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'auct_step')->textInput() ?>

    <?= $form->field($model, 'publish_time')->textInput() ?>

    <?= $form->field($model, 'start_time')->textInput() ?>

    <?= $form->field($model, 'end_time')->textInput() ?>

    <?= $form->field($model, 'result_time')->textInput() ?>

    <?= $form->field($model, 'debtor_id')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'organizer_id')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'link')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'fedresurs_link')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'case_number')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/trade/create.php
<?php

use yii\helpers\Html;

$this->title = 'Create Lot';
$this->params['breadcrumbs'][] = ['label' => 'Lots', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="lot-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/trade/index.php
<?php

use app\models\User;
use yii\helpers\Html;
use yii\helpers\Url;

use yii\grid\GridView;
use yii\widgets\ListView;
use yii\widgets\Pjax;
use yii\helpers\StringHelper;

use app\components\CustomLinkPager;

$this->title = Yii::$app->params['meta']['title']['trade'];
$this->registerMetaTag(['name' => 'description', 'content' => Yii::$app->params['meta']['desc']['trade']]);

$this->params['breadcrumbs'][] =  Yii::$app->params['meta']['h1']['trade'];
?>
<div class="lots-index">
    <?php Pjax::begin(['clientOptions' => ['method' => 'POST']]); ?>    


    <div class="row">
        <div class="col-lg-12">

            <div class="panel panel-default">
              <div class="panel-body">
                <?php echo $this->render('_search', ['model' => $searchModel]); ?>
              </div>

            </div>

        </div>

    </div>

    <div class="row">
        <div class="col-lg-12">
            <p class="total-count">Найдено по запросу: <strong><?=$total?></strong></p>
            <div class="panel panel-default">
                <div class="panel-body lots-list-panel">
                <?php if (count($lots) == 0): ?>
                    <br>
                    <p class="lead text-center">Торги не найдены</p>
                <?php endif ?>
                <?php foreach ($lots as $model): ?>
                    <div class="row lot-item">
                        <div class="col-lg-5">
                            <div class="lot-item-name">
                                <a data-pjax="0" class="table-link" href="<?= Url::to(['trade/view', 'id' => $model->id]); ?>">
                                    Торги № <?= $model->id?> 
                                </a>
                            </div>
                            <p>
                                <span class="label label-primary">
                                <?php if ($model->type_id == 1): ?>
                                    <i class="fa fa-arrow-down" style="color: orange;"></i> 
                                <?php else: ?>
                                    <i class="fa fa-arrow-up" style="color: lime;"></i> 
                                <?php endif ?>
                                    
                                    <?= number_format($model->now_price, 2, ',', ' ')?> руб.
                                </span>
                            </p>
                            <p><?= StringHelper::truncate($model->description, 470, '...')?></p>
                        </div>
                        <div class="col-lg-3">
                            <p><strong>Категория:</strong> <?= $model->category->name?></p>
                            <p><strong>Регион:</strong> <?= $model->region->name?></p>
                            <p>
                                <strong>Площадка:</strong> 
                                <?php if (User::isClient()): ?>
                                    <?= $model->platform->name?>
                                <?php else: ?>
                                    ▒▒▒▒▒▒▒▒
                                <?php endif ?>
                            </p>
                        </div>
                        <div class="col-lg-2">
                            <p class="text-center">
                                <?= Yii::$app->formatter->asDatetime($model->start_time, "php: d.m.y ") ?>
                                -
                                <?= Yii::$app->formatter->asDatetime($model->end_time, "php: d.m.y ") ?>
                            </p>
                            <p class="text-center pagado"><?= $model->status->name?></p>
                        </div>
                        <!-- <div class="col-lg-1"></div> -->
                        <div class="col-lg-2">
                        
                            <?php if (!Yii::$app->user->isGuest): ?>
                                <div class="text-center bs-component">
                                    <?php if ($model->lotFavorite): ?>
                                        <button onclick="addFavorite(this)" data-id="<?= $model->id?>" type="button" class="add-favorite btn btn-xs btn-default" data-toggle="tooltip" data-placement="top" title="" data-original-title="Избранное">
                                            <i class="fa fa-minus"></i>
                                        </button>
                                    <?php else: ?>
                                        <button onclick="addFavorite(this)" data-id="<?= $model->id?>" type="button" class="add-favorite btn btn-xs btn-success" data-toggle="tooltip" data-placement="top" title="" data-original-title="Избранное">
                                            <i class="fa fa-plus"></i>
                                        </button>
                                    <?php endif ?>

                                    <?php if ($model->lotMonitor): ?>
                                        <button onclick="addMonitor(this)" data-id="<?= $model->id?>" type="button" class="add-monitor btn btn-xs btn-default" data-toggle="tooltip" data-placement="top" title="" data-original-title="Следить">
                                            <i class="fa fa-search-minus"></i>
                                        </button>
                                    <?php else: ?>
                                        <button onclick="addMonitor(this)" data-id="<?= $model->id?>" type="button" class="add-monitor btn btn-xs btn-warning" data-toggle="tooltip" data-placement="top" title="" data-original-title="Следить">
                                            <i class="fa fa-search-plus"></i>
                                        </button>
                                    <?php endif ?>

                                    <button onclick="addTrash(this)" data-id="<?= $model->id?>" type="button" class="add-trash btn btn-xs btn-danger" data-toggle="tooltip" data-placement="top" title="" data-original-title="Мусор">
                                        <i class="fa fa-trash"></i>
                                    </button>
                                </div>
                            <?php endif ?>
                               

                        </div>
                    </div>


                    <?php endforeach ?>


                <?php
                    echo CustomLinkPager::widget([
                        'pagination' => $pages,
                    ]);
                ?>
                </div>

            </div>

        </div>
    </div>
    <?php Pjax::end(); ?>


</div>

views/trade/update.php
<?php

use yii\helpers\Html;

$this->title = 'Update Lot: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Lots', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="lot-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/trade/view-guest.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\DetailView;
use miloschuman\highcharts\Highcharts;
use yii\helpers\StringHelper;

$this->title = StringHelper::truncate($model->description, 50, '...').' - торги по банкротству | Madetrade.ru';
$this->registerMetaTag(['name' => 'description', 'content' => 'Торги по банкротству - '.StringHelper::truncate($model->description, 150, '...') ]);

$this->params['breadcrumbs'][] = ['label' => 'Торги', 'url' => ['index']];
$this->params['breadcrumbs'][] = 'Торги № '.$model->id;

?>

<div class="lot-index">

    <div class="row">
        <div class="col-lg-8">
            <div class="panel panel-default">
                <div class="panel-heading custom-panel-heading">
                    Торги № <?= $model->id ?>
                    <span class="general-price pull-right ">
                        <?php if ($model->type_id == 1): ?>
                            <i class="fa fa-arrow-down" style="color: red;"></i> 
                        <?php else: ?>
                            <i class="fa fa-arrow-up" style="color: green;"></i>
                        <?php endif ?>
                        <?= number_format($model->now_price, 2, ',', ' ')?> 
                        <i class="fa fa-rub"></i>
                    </span>
                </div>
                <div class="panel-body">
                    <p><?= $model->description ?></p>

                    <?php if (!Yii::$app->user->isGuest): ?>
                    <div class="bs-component pull-left">
                        <?php if ($model->lotFavorite): ?>
                            <button onclick="addFavorite(this)" data-id="<?= $model->id?>" type="button" class="add-favorite btn btn-xs btn-default" data-toggle="tooltip" data-placement="top" title="" data-original-title="Избранное">
                                <i class="fa fa-minus"></i>
                            </button>
                        <?php else: ?>
                            <button onclick="addFavorite(this)" data-id="<?= $model->id?>" type="button" class="add-favorite btn btn-xs btn-success" data-toggle="tooltip" data-placement="top" title="" data-original-title="Избранное">
                                <i class="fa fa-plus"></i>
                            </button>
                        <?php endif ?>

                        <?php if ($model->lotMonitor): ?>
                            <button onclick="addMonitor(this)" data-id="<?= $model->id?>" type="button" class="add-monitor btn btn-xs btn-default" data-toggle="tooltip" data-placement="top" title="" data-original-title="Следить">
                                <i class="fa fa-search-minus"></i>
                            </button>
                        <?php else: ?>
                            <button onclick="addMonitor(this)" data-id="<?= $model->id?>" type="button" class="add-monitor btn btn-xs btn-warning" data-toggle="tooltip" data-placement="top" title="" data-original-title="Следить">
                                <i class="fa fa-search-plus"></i>
                            </button>
                        <?php endif ?>

                        <button onclick="addTrash(this)" data-id="<?= $model->id?>" type="button" class="add-trash btn btn-xs btn-danger" data-toggle="tooltip" data-placement="top" title="" data-original-title="Мусор">
                            <i class="fa fa-trash"></i>
                        </button>
                    </div>
                    <?php endif ?>

                    <div class="pull-right">
                        <i class="fa fa-map-marker"></i>
                        <?=$model->region->name?>
                    </div>

                </div>
                <table class="table table-striped table-hover">
                    <colgroup> <col class="col-lg-3"> <col class="col-lg-9"> </colgroup>
                    <tbody>
                        <tr>
                            <th>Начальная цена</th>
                            <td><i class="fa fa-rub"></i> <?= number_format($model->start_price, 2, ',', ' ')?> </td>
                        </tr>
                        <tr>
                            <th>Текущая цена</th>
                            <td><i class="fa fa-rub"></i> <?= number_format($model->now_price, 2, ',', ' ')?> </td>
                        </tr>
<!--                         <tr>
                            <th>Рыночная цена</th>
                            <td><i class="fa fa-rub"></i> <?= number_format($model->market_price, 2, ',', ' ')?> </td>
                        </tr> -->
                        <tr>
                            <th>Задаток</th>
                            <td><i class="fa fa-rub"></i> ▒▒▒▒▒▒▒▒</td>
                        </tr>
                        <tr>
                            <th>Шаг аукциона</th>
                            <td><i class="fa fa-rub"></i> ▒▒▒▒▒▒▒▒</td>
                        </tr>
                        <tr>
                            <th>Номер дела</th>
                            <td><i class="fa fa-book"></i> ▒▒▒▒▒▒▒▒</td>
                        </tr>
                        <tr>
                            <th>Ссылка на торги</th>
                            <td><i class="fa fa-external-link"></i> ▒▒▒▒▒▒▒▒</td>
                        </tr>
                    </tbody>
                </table>
            </div>


            <?php if ($model->organizer): ?>
            <!-- ОРГАНИЗАТОР ТОРГОВ -->
            <div class="panel panel-default">
                <div class="panel-heading custom-panel-heading">Организатор торгов</div>
                <table class="table table-striped table-hover">
                    <colgroup> <col class="col-lg-3"> <col class="col-lg-9"> </colgroup>
                    <tbody>
                        <tr>
                            <th>Наименование</th>
                            <td><a class="table-link" href="<?= Url::to(['organizers/view', 'id' => $model->organizer->id ]); ?>"><?= $model->organizer->short_name?> </a></td>
                        </tr>
                        <tr>
                            <th>ИНН</th>
                            <td>▒▒▒▒▒▒▒▒ </td>
                        </tr>
                        <tr>
                            <th>Адрес</th>
                            <td><i class="fa fa-map-marker"></i> ▒▒▒▒▒▒▒▒ </td>
                        </tr>
                        <tr>
                            <th>Контактное лицо</th>
                            <td><i class="fa fa-user"></i> ▒▒▒▒▒▒▒▒</td>
                        </tr>
                        <tr>
                            <th>Телефон</th>
                            <td><i class="fa fa-phone"></i> ▒▒▒▒▒▒▒▒ </td>
                        </tr>
                        <tr>
                            <th>Email</th>
                            <td><i class="fa fa-envelope"></i> ▒▒▒▒▒▒▒▒ </td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <?php endif ?>

            
            <?php if ($model->arbitr): ?>
            <!-- АРБИТРАЖНЫЙ УПРАВЛЯЮЩИЙ -->
            <div class="panel panel-default">
                <div class="panel-heading custom-panel-heading">Арбитражный управляющий</div>
                <table class="table table-striped table-hover">
                    <colgroup> <col class="col-lg-3"> <col class="col-lg-9"> </colgroup>
                    <tbody>
                        <tr>
                            <th>Наименование</th>
                            <td><a class="table-link" href="<?= Url::to(['arbitr/view', 'id' => $model->arbitr->id ]); ?>"><?= $model->arbitr->name?> </a></td>
                        </tr>
                        <tr>
                            <th>ИНН</th>
                            <td>▒▒▒▒▒▒▒▒ </td>
                        </tr>
                        <tr>
                            <th>Адрес</th>
                            <td><i class="fa fa-map-marker"></i> ▒▒▒▒▒▒▒▒ </td>
                        </tr>
                        <tr>
                            <th>Контактное лицо</th>
                            <td><i class="fa fa-user"></i> ▒▒▒▒▒▒▒▒ </td>
                        </tr>
                        <tr>
                            <th>Телефон</th>
                            <td><i class="fa fa-phone"></i> ▒▒▒▒▒▒▒▒ </td>
                        </tr>
                        <tr>
                            <th>Email</th>
                            <td><i class="fa fa-envelope"></i> ▒▒▒▒▒▒▒▒ </td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <?php endif ?>


            <?php if ($model->debtor): ?>
            <!-- ДОЛЖНИК -->
            <div class="panel panel-default">
                <div class="panel-heading custom-panel-heading">Банкрот</div>
                <table class="table table-striped table-hover">
                    <colgroup> <col class="col-lg-3"> <col class="col-lg-9"> </colgroup>
                    <tbody>
                        <tr>
                            <th>Наименование</th>
                            <td><a class="table-link" href="<?= Url::to(['debtors/view', 'id' => $model->debtor->id ]); ?>"><?= $model->debtor->short_name?> </a></td>
                        </tr>
                        <tr>
                            <th>ИНН</th>
                            <td>▒▒▒▒▒▒▒▒ </td>
                        </tr>
                        <tr>
                            <th>Адрес</th>
                            <td><i class="fa fa-map-marker"></i> ▒▒▒▒▒▒▒▒ </td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <?php endif ?>


        </div>
        <div class="col-lg-4">

            <!-- ДАТЫ -->
            <div class="panel panel-default">
                <div class="panel-heading">
                    <strong>Информация</strong>
                </div>
                <?= DetailView::widget([
                    'model' => $model,
                    'options' => [
                        'class' => 'table table-striped table-hover',
                    ],
                    'attributes' => [
                        [
                            'attribute' => 'publish_time',
                            'value' => Yii::$app->formatter->asDatetime($model->publish_time, "php: d.m.Y  h:i"),
                        ], 
                        [
                            'attribute' => 'start_time',
                            'value' => Yii::$app->formatter->asDatetime($model->start_time, "php: d.m.Y  h:i"),
                        ], 
                        [
                            'attribute' => 'end_time',
                            'value' => Yii::$app->formatter->asDatetime($model->end_time, "php: d.m.Y  h:i"),
                        ], 
                        [
                            'attribute' => 'result_time',
                            'value' => Yii::$app->formatter->asDatetime($model->result_time, "php: d.m.Y  h:i"),
                        ], 
                    ],
                ]) ?>
            </div>


            <?php if ($intervals): ?>


            <div class="panel panel-default">
                <?php 
                    echo Highcharts::widget([
                       'options' => [
                            'legend' => ['enabled' => false],
                            'credits' => false,
                            'chart' => [
                                'type' => 'spline',
                            ],
                            'title' => ['text' => 'График понижения цены'],
                            'xAxis' => [
                                'categories' => array_column($intervals, 'start_time'),
                            ],
                            'yAxis' => [
                                'title' => ['text' => 'Цена на этапе']
                            ],
                            'series' => 
                            [
                                [
                                    'name' => 'Цена',
                                    'data' => array_column($intervals, 'price'),
                                ],
                                 // ['name' => 'Джон', 'data' => [5, 7, 3]]
                            ]
                       ]
                    ]);

                 ?>
            </div>

            <?php endif ?>


        </div>
    </div>

    <div class="row">
        <div class="col-lg-12"> 
            
        </div>
    </div>

</div>