models/User.php
<?php

namespace app\models;

use Yii;
use yii\base\NotSupportedException;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\web\IdentityInterface;

class User extends \yii\db\ActiveRecord implements IdentityInterface
{
    const STATUS_DELETED = 0;
    const STATUS_ACTIVE = 10;

    const ROLE_USER = 10;
    const ROLE_CLIENT = 20;
    // const ROLE_VIP = 30;
    const ROLE_MODER = 50;
    const ROLE_ADMIN = 100;

    public static function tableName()
    {
        return '{{%user}}';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            ['role', 'default', 'value' => self::ROLE_USER],
            ['status', 'default', 'value' => self::STATUS_ACTIVE],
            ['status', 'in', 'range' => [self::STATUS_ACTIVE, self::STATUS_DELETED]],
        ];
    }
    
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'username' => 'Пользователь',
            'email' => 'Email',
            'created_at' => 'Дата регистрации',
            'updated_at' => 'Дата обновления',
            'role' => 'Роль',
            'tariff_time' => 'Дата окончания подписки',
            'avatar' => 'Аватар',
        ];
    }

    /**
     * @inheritdoc
     */
    public static function findIdentity($id)
    {
        return static::findOne(['id' => $id]);
    }

    /**
     * @inheritdoc
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        throw new NotSupportedException('"findIdentityByAccessToken" is not implemented.');
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        return static::findOne(['username' => $username]);
    }

    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->getPrimaryKey();
    }

    public function getUserName()
    {
        return $this->username;
    }

    // название роли пользователя
    public function getUserRoleName()
    {
        $rolename = 'Пользователь';
        switch ($this->role) {
            case 100:
                $rolename = 'Администратор';
                break;
            case 50:
                $rolename = 'Модератор';
                break;
            case 20;
                $rolename = 'Клиент';
                break;
            case 10:
                $rolename = 'Пользователь';
                break;
            default:
                $rolename = 'Пользователь';
                break;
        }
        return $rolename;
    }

    // является ли юзер клиентов с оплаченой подпиской (или админом, модером)
    public static function isClient()
    {
        return Yii::$app->user->identity->role >= 20 ? true : false;
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey()
    {
        return $this->authKey;
    }   

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey)
    {
        return $this->getAuthKey() === $authKey;
    }

    public static function findByPasswordResetToken($token)
    {
        if (!static::isPasswordResetTokenValid($token)) {
            return null;
        }

        return static::findOne([
            'password_reset_token' => $token,
            'status' => self::STATUS_ACTIVE,
        ]);
    }

    /**
     * Finds out if password reset token is valid
     *
     * @param string $token password reset token
     * @return bool
     */
    public static function isPasswordResetTokenValid($token)
    {
        if (empty($token)) {
            return false;
        }

        $timestamp = (int) substr($token, strrpos($token, '_') + 1);
        $expire = Yii::$app->params['user.passwordResetTokenExpire'];
        return $timestamp + $expire >= time();
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return bool if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return Yii::$app->security->validatePassword($password, $this->password_hash);
    }

    /**
     * Generates password hash from password and sets it to the model
     *
     * @param string $password
     */
    public function setPassword($password)
    {
        $this->password_hash = Yii::$app->security->generatePasswordHash($password);
    }

    /**
     * Generates "remember me" authentication key
     */
    public function generateAuthKey()
    {
        $this->auth_key = Yii::$app->security->generateRandomString();
    }

    /**
     * Generates new password reset token
     */
    public function generatePasswordResetToken()
    {
        $this->password_reset_token = Yii::$app->security->generateRandomString() . '_' . time();
    }

    /**
     * Removes password reset token
     */
    public function removePasswordResetToken()
    {
        $this->password_reset_token = null;
    }
}

controllers/UserController.php
<?php
namespace app\controllers;

use Yii;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

use app\models\forms\LoginForm;
use app\models\forms\PasswordResetRequestForm;
use app\models\forms\ResetPasswordForm;
use app\models\forms\SignupForm;
use app\models\forms\ChangeEmailForm;
use app\models\forms\ChangePasswordForm;
use app\models\forms\ChangeAvatarForm;
use app\models\forms\UsePromoForm;

use yii\web\UploadedFile;

use app\models\User;

/**
 * User controller
 */
class UserController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => [
                    'login', 
                    'logout', 
                    'signup',
                    'index', 
                    'email', 
                    'password', 
                    'avatar'
                ],
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['login', 'signup'],
                        'roles' => ['?'],
                    ],
                    [
                        'allow' => true,
                        'actions' => [
                            'logout', 
                            'index', 
                            'email', 
                            'password', 
                            'avatar'
                        ],
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex()
    {
        return $this->render('index', [
            'user' => $this->findModel(),
        ]);
    }

    public function actionPromo()
    {
        $user = $this->findModel();
        $model = new UsePromoForm();
        
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $model->activatePromo();
            return $this->redirect(['index']);
        } else {
            return $this->render('promo', [
                'user' => $user,
                'model' => $model,
            ]);
        }
    }

    public function actionEmail()
    {
        $user = $this->findModel();
        $model = new ChangeEmailForm($user);
     
        if ($model->load(Yii::$app->request->post()) && $model->update()) {
            return $this->redirect(['index']);
        } else {
            return $this->render('email', [
                'user' => $user,
                'model' => $model,
            ]);
        }
    }

    public function actionPassword()
    {
        $user = $this->findModel();
        $model = new ChangePasswordForm($user);
 
        if ($model->load(Yii::$app->request->post()) && $model->changePassword()) {
            return $this->redirect(['index']);
        } else {
            return $this->render('password', [
                'user' => $user,
                'model' => $model,
            ]);
        }
    }


    public function actionAvatar()
    {
        $user = $this->findModel();
        $model = new ChangeAvatarForm($user);

        if (Yii::$app->request->isPost) {
            $model->avatar = UploadedFile::getInstance($model, 'avatar');
            if ($model->upload()) {
                return $this->redirect(['index']);
            }
        }

        return $this->render('avatar', [
                'user' => $user,
                'model' => $model,
            ]);
    }



    private function findModel()
    {
        return User::findOne(Yii::$app->user->identity->getId());
    }

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Signs user up.
     *
     * @return mixed
     */
    public function actionSignup()
    {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->goHome();
                }
            }
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for email provided.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'New password was saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }
}

views/user/avatar.php
<?php 
use yii\widgets\ActiveForm;
use yii\helpers\Html;
use yii\helpers\Url;

$this->title = 'Профиль';

$this->params['breadcrumbs'][] = $this->title;

?>

<div class="row">
    <div class="col-lg-12">

        <div class="panel panel-default">
            <div class="panel-heading">
                Профиль
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-3">
                        <p>
                            <?php $avatar_label = Yii::$app->user->identity->avatar ? '@web/uploads/'.$user->avatar : '@web/img/ava-profile.svg'; ?>
                            <?=Html::img( $avatar_label, ['class' => 'center-block img-responsive img-thumbnail'])?>
                        </p>
                        <div class="list-group">
                          <a href="<?= Url::to(['/user/']); ?>" class="list-group-item">Профиль</a>
                          <a href="<?= Url::to(['/user/avatar']); ?>" class="list-group-item">Изменить аватар</a>
                          <a href="<?= Url::to(['/user/password']); ?>" class="list-group-item">Изменить пароль</a>
                          <a href="<?= Url::to(['/user/email']); ?>" class="list-group-item">Изменить email</a>
                          <a href="<?= Url::to(['/user/promo']); ?>" class="list-group-item">Ввести промо-код</a>
                        </div>
                        
                    </div>

                    
                    <div class="col-lg-9">
                        <h2><?=$user->username?></h2>
                        <hr>



                        <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]) ?>

                        <?= $form->field($model, 'avatar')->fileInput()->label(false) ?>

                        <div class="form-group">
                            <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
                        </div>

                        <?php ActiveForm::end() ?>






                    </div>
                </div>
            </div>

        </div>

    </div>

</div>

views/user/email.php
<?php 
use yii\widgets\ActiveForm;
use yii\helpers\Html;
use yii\helpers\Url;

$this->title = 'Профиль';

$this->params['breadcrumbs'][] = $this->title;

?>

<div class="row">
    <div class="col-lg-12">

        <div class="panel panel-default">
            <div class="panel-heading">
                Профиль
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-3">
                        <p>
                            <?php $avatar_label = Yii::$app->user->identity->avatar ? '@web/uploads/'.$user->avatar : '@web/img/ava-profile.svg'; ?>
                            <?=Html::img( $avatar_label, ['class' => 'center-block img-responsive img-thumbnail'])?>
                        </p>
                        <div class="list-group">
                          <a href="<?= Url::to(['/user/']); ?>" class="list-group-item">Профиль</a>
                          <a href="<?= Url::to(['/user/avatar']); ?>" class="list-group-item">Изменить аватар</a>
                          <a href="<?= Url::to(['/user/password']); ?>" class="list-group-item">Изменить пароль</a>
                          <a href="<?= Url::to(['/user/email']); ?>" class="list-group-item">Изменить email</a>
                          <a href="<?= Url::to(['/user/promo']); ?>" class="list-group-item">Ввести промо-код</a>
                        </div>
                        
                    </div>

                    
                    <div class="col-lg-9">
                        <h2><?=$user->username?></h2>
                        <hr>
                        <?php $form = ActiveForm::begin(); ?>

                        <?= $form->field($model, 'email')->textInput() ?>

                        <div class="form-group">
                            <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
                        </div>

                        <?php ActiveForm::end(); ?>


                    </div>
                </div>
            </div>

        </div>

    </div>

</div>

views/user/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/user/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
$this->title = 'Профиль';

$this->params['breadcrumbs'][] = $this->title;

?>

<div class="row">
    <div class="col-lg-12">

        <div class="panel panel-default">
            <div class="panel-heading">
                Профиль
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-3">
                        <p>
                            <?php $avatar_label = Yii::$app->user->identity->avatar ? '@web/uploads/'.$user->avatar : '@web/img/ava-profile.svg'; ?>
                            <?=Html::img( $avatar_label, ['class' => 'center-block img-responsive img-thumbnail'])?>
                        </p>
                        <div class="list-group">
                          <a href="<?= Url::to(['/user/']); ?>" class="list-group-item">Профиль</a>
                          <a href="<?= Url::to(['/user/avatar']); ?>" class="list-group-item">Изменить аватар</a>
                          <a href="<?= Url::to(['/user/password']); ?>" class="list-group-item">Изменить пароль</a>
                          <a href="<?= Url::to(['/user/email']); ?>" class="list-group-item">Изменить email</a>
                          <a href="<?= Url::to(['/user/promo']); ?>" class="list-group-item">Ввести промо-код</a>
                        </div>
                        
                    </div>

                    
                    <div class="col-lg-9">
                        <h2><?=$user->username?></h2>
                        <hr>
                        <p><strong>Статус:</strong> <?=$user->getUserRoleName()?></p>
                        <p><strong>Дата регистрации:</strong> 
                        <?= Yii::$app->formatter->asDate($user->created_at, 'php: d.m.Y ') ?>
                        </p>
                        <p><strong>Подписка:</strong> 
                        <?=Yii::$app->user->identity->tariff_time ? 'До '.Yii::$app->formatter->asDate(Yii::$app->user->identity->tariff_time, 'php: d.m.Y ') : 'Нет' ?>
                        </p>
                        <p><strong>Email:</strong> <?=$user->email?></p>

                    </div>
                </div>
            </div>

        </div>

    </div>

</div>

views/user/login.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = Yii::$app->params['meta']['title']['login'];
$this->registerMetaTag(['name' => 'description', 'content' => Yii::$app->params['meta']['desc']['login']]);

$this->params['breadcrumbs'][] = Yii::$app->params['meta']['h1']['login'];
?>


<div class="row row-centered">
    <div class="col-lg-5 col-centered">
        <h1><?= Html::encode(Yii::$app->params['meta']['h1']['login']) ?></h1>

        <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>

            <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

            <?= $form->field($model, 'password')->passwordInput() ?>

            <?= $form->field($model, 'rememberMe')->checkbox() ?>

            <div style="color:#999;margin:1em 0">
                Если вы забыли свой пароль вы можете <?= Html::a('восстановить его', ['user/request-password-reset']) ?>.
            </div>

            <div class="text-center form-group">
                <?= Html::submitButton('Войти', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>

        <?php ActiveForm::end(); ?>
    </div>
</div>

views/user/password.php
<?php 

use yii\widgets\ActiveForm;
use yii\helpers\Html;
use yii\helpers\Url;

$this->title = 'Профиль';

$this->params['breadcrumbs'][] = $this->title;

?>

<div class="row">
    <div class="col-lg-12">

        <div class="panel panel-default">
            <div class="panel-heading">
                Профиль
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-3">
                        <p>
                            <?php $avatar_label = Yii::$app->user->identity->avatar ? '@web/uploads/'.$user->avatar : '@web/img/ava-profile.svg'; ?>
                            <?=Html::img( $avatar_label, ['class' => 'center-block img-responsive img-thumbnail'])?>
                        </p>
                        <div class="list-group">
                          <a href="<?= Url::to(['/user/']); ?>" class="list-group-item">Профиль</a>
                          <a href="<?= Url::to(['/user/avatar']); ?>" class="list-group-item">Изменить аватар</a>
                          <a href="<?= Url::to(['/user/password']); ?>" class="list-group-item">Изменить пароль</a>
                          <a href="<?= Url::to(['/user/email']); ?>" class="list-group-item">Изменить email</a>
                          <a href="<?= Url::to(['/user/promo']); ?>" class="list-group-item">Ввести промо-код</a>
                        </div>
                        
                    </div>

                    
                    <div class="col-lg-9">
                        <h2><?=$user->username?></h2>
                        <hr>
                        <?php $form = ActiveForm::begin(); ?>
     
                        <?= $form->field($model, 'currentPassword')->passwordInput(['maxlength' => true]) ?>
                        <?= $form->field($model, 'newPassword')->passwordInput(['maxlength' => true]) ?>
                        <?= $form->field($model, 'newPasswordRepeat')->passwordInput(['maxlength' => true]) ?>
                 
                        <div class="form-group">
                            <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
                        </div>

                        <?php ActiveForm::end(); ?>


                    </div>
                </div>
            </div>

        </div>

    </div>

</div>

views/user/promo.php
<?php 
use yii\widgets\ActiveForm;
use yii\helpers\Html;
use yii\helpers\Url;

$this->title = 'Профиль';

$this->params['breadcrumbs'][] = $this->title;

?>

<div class="row">
    <div class="col-lg-12">

        <div class="panel panel-default">
            <div class="panel-heading">
                Профиль
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-3">
                        <p>
                            <?php $avatar_label = Yii::$app->user->identity->avatar ? '@web/uploads/'.$user->avatar : '@web/img/ava-profile.svg'; ?>
                            <?=Html::img( $avatar_label, ['class' => 'center-block img-responsive img-thumbnail'])?>
                        </p>
                        <div class="list-group">
                          <a href="<?= Url::to(['/user/']); ?>" class="list-group-item">Профиль</a>
                          <a href="<?= Url::to(['/user/avatar']); ?>" class="list-group-item">Изменить аватар</a>
                          <a href="<?= Url::to(['/user/password']); ?>" class="list-group-item">Изменить пароль</a>
                          <a href="<?= Url::to(['/user/email']); ?>" class="list-group-item">Изменить email</a>
                          <a href="<?= Url::to(['/user/promo']); ?>" class="list-group-item">Ввести промо-код</a>
                        </div>
                        
                    </div>

                    
                    <div class="col-lg-9">
                        <h2><?=$user->username?></h2>
                        <hr>
                        <?php $form = ActiveForm::begin(); ?>

                        <?= $form->field($model, 'promo_key')->textInput() ?>

                        <div class="form-group">
                            <?= Html::submitButton('Активировать', ['class' => 'btn btn-success']) ?>
                        </div>

                        <?php ActiveForm::end(); ?>


                    </div>
                </div>
            </div>

        </div>

    </div>

</div>

views/user/requestPasswordResetToken.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Восстановление пароля';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-request-password-reset">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Пожалуйста, введите Ваш email, на него будет отправлена информация для восстановления пароля.</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'request-password-reset-form']); ?>

                <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Отправить', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

views/user/resetPassword.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Reset password';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-reset-password">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please choose your new password:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'reset-password-form']); ?>

                <?= $form->field($model, 'password')->passwordInput(['autofocus' => true]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Save', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

views/user/signup.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = Yii::$app->params['meta']['title']['signup'];
$this->registerMetaTag(['name' => 'description', 'content' => Yii::$app->params['meta']['desc']['signup']]);

$this->params['breadcrumbs'][] = Yii::$app->params['meta']['h1']['signup'];
?>

<div class="row row-centered">
    <div class="col-lg-5 col-centered">
        <h1><?= Html::encode(Yii::$app->params['meta']['h1']['signup']) ?></h1>
        <?php $form = ActiveForm::begin(['id' => 'form-signup']); ?>

            <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

            <?= $form->field($model, 'email') ?>

            <?= $form->field($model, 'password')->passwordInput() ?>
            
            <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                    'template' => '<div class="row"><div class="col-lg-4">{image}</div><div class="col-lg-8">{input}</div></div>',
                ]) ?>
            <hr>
            <div class="text-center form-group">
                <?= Html::submitButton('Зарегистрироваться', ['class' => 'btn btn-primary', 'name' => 'signup-button']) ?>
            </div>

        <?php ActiveForm::end(); ?>
    </div>
</div>